import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Label } from "@/components/ui/label";
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col h-screen bg-[#002734] ${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          backgroundImage:
            "url(https://hebbkx1anhila5yf.public.blob.vercel-storage.com/builtt_personal_cover_without_logo-kkH3tDxwbYuPQef78SKUFE53nupNRF.png)",
          backgroundSize: "auto",
          backgroundRepeat: "repeat-y",
          backgroundPosition: "top right",
        }}
      >
        <div className="flex flex-row">
          <Label className="text-white">
            <Link href="/tricks">Tricks</Link>
          </Label>
        </div>
        {children}
      </body>
    </html>
  );
}
